/* eslint-disable prettier/prettier */
const actions = {
    GET_USER_REGISTER: 'GET_USER_REGISTER',
    SET_USER_REGISTER: 'SET_USER_REGISTER',
    GET_USER_LOGIN: 'GET_USER_LOGIN',
    SET_USER_LOGIN: 'SET_USER_LOGIN',
    GET_USER_PROFILE: 'GET_USER_PROFILE',
    SET_USER_PROFILE: 'SET_USER_PROFILE',
    SET_IS_LOGIN:'SET_IS_LOGIN',
    GET_COMPLETED_FLIGHT_TICKETS:'GET_COMPLETED_FLIGHT_TICKETS',
    GET_CANCELLED_FLIGHT_TICKETS:'GET_CANCELLED_FLIGHT_TICKETS',
    GET_UPCOMING_FLIGHT_TICKETS:'GET_UPCOMING_FLIGHT_TICKETS',
    GET_COMPLETED_HOTEL_TICKETS:'GET_COMPLETED_HOTEL_TICKETS',
    GET_CANCELLED_HOTEL_TICKETS:'GET_CANCELLED_HOTEL_TICKETS',
    GET_UPCOMING_HOTEL_TICKETS:'GET_UPCOMING_HOTEL_TICKETS',
}

export default actions