/* eslint-disable prettier/prettier */
const actions = {
    GET_USER_REGISTER: 'GET_USER_REGISTER',
    SET_USER_REGISTER: 'SET_USER_REGISTER',
    GET_USER_LOGIN: 'GET_USER_LOGIN',
    SET_USER_LOGIN: 'SET_USER_LOGIN',
    GET_USER_PROFILE: 'GET_USER_PROFILE',
    SET_USER_PROFILE: 'SET_USER_PROFILE',
    SET_IS_LOGIN:'SET_IS_LOGIN',
    GET_COMPLETED_FLIGHT_TICKETS:'GET_COMPLETED_FLIGHT_TICKETS',
    GET_CANCELLED_FLIGHT_TICKETS:'GET_CANCELLED_FLIGHT_TICKETS',
    GET_UPCOMING_FLIGHT_TICKETS:'GET_UPCOMING_FLIGHT_TICKETS',
    GET_COMPLETED_HOTEL_TICKETS:'GET_COMPLETED_HOTEL_TICKETS',
    GET_CANCELLED_HOTEL_TICKETS:'GET_CANCELLED_HOTEL_TICKETS',
    GET_UPCOMING_HOTEL_TICKETS:'GET_UPCOMING_HOTEL_TICKETS',
    GET_HOTEL_TICKETS_DETAILS:'GET_HOTEL_TICKETS_DETAILS',
    SET_HOTEL_TICKETS_DETAILS:'SET_HOTEL_TICKETS_DETAILS',
    GET_ADD_TRAVELLER_FORM:'GET_ADD_TRAVELLER_FORM:',
    SET_ADD_TRAVELLER_SEARCH_BY_NAME:'SET_ADD_TRAVELLER_SEARCH_BY_NAME',
    GET_ADD_TRAVELLER_COUNTRY_CODE:'GET_ADD_TRAVELLER_COUNTRY_CODE',
    GET_ADD_TRAVELLER_COUNTRY_ISSUING:'GET_ADD_TRAVELLER_COUNTRY_ISSUING',
    GET_ADD_TRAVELLER_NATIONALITY:'GET_ADD_TRAVELLER_NATIONALITY',
    GET_ADD_TRAVELLER_VALUE:"GET_ADD_TRAVELLER_VALUE",
    GET_ADD_TRAVELLER_TOKEN:"GET_ADD_TRAVELLER_TOKEN",
    SET_ADD_TRAVELLER_TOKEN:"SET_ADD_TRAVELLER_TOKEN",

}
export default actions