/* eslint-disable prettier/prettier */
const actions = {
    GET_USER_REGISTER: 'GET_USER_REGISTER',
    SET_USER_REGISTER: 'SET_USER_REGISTER',
    GET_USER_LOGIN: 'GET_USER_LOGIN',
    SET_USER_LOGIN: 'SET_USER_LOGIN',
    GET_USER_PROFILE: 'GET_USER_PROFILE',
    SET_USER_PROFILE: 'SET_USER_PROFILE',
    SET_IS_LOGIN:'SET_IS_LOGIN',
}

export default actions