/* eslint-disable prettier/prettier */
const actions = {
SET_FLIGHT_SEARCH_BY_NAME:'SET_FLIGHT_SEARCH_BY_NAME',
GET_FLIGHT_SEARCH_FROM_BY_NAME:'GET_FLIGHT_SEARCH_FROM_BY_NAME',
GET_FLIGHT_SEARCH_TO_BY_NAME:'GET_FLIGHT_SEARCH_TO_BY_NAME',
SET_FLIGHT_SEARCH:'SET_FLIGHT_SEARCH',
GET_FLIGHT_SEARCH:'GET_FLIGHT_SEARCH',
SET_FARE_RULES:'SET_FARE_RULES',
GET_FARE_RULES:'GET_FARE_RULES',
SET_REVALIDATE:'SET_REVALIDATE',
GET_REVALIDATE:'GET_REVALIDATE',

}

export default actions