/* eslint-disable prettier/prettier */
const actions = {
SET_FLIGHT_SEARCH_BY_NAME:'SET_FLIGHT_SEARCH_BY_NAME',
GET_FLIGHT_SEARCH_FROM_BY_NAME:'GET_FLIGHT_SEARCH_FROM_BY_NAME',
GET_FLIGHT_SEARCH_TO_BY_NAME:'GET_FLIGHT_SEARCH_TO_BY_NAME',
SET_FLIGHT_SEARH:'SET_FLIGHT_SEARH'
}

export default actions