/* eslint-disable prettier/prettier */
const actions = {
GET_POPULAR_PLACES:'GET_POPULAR_PLACES',
SET_POPULAR_PLACE_DETAILS:'SET_POPULAR_PLACE_DETAILS',
GET_POPULAR_PLACE_DETAILS:'GET_POPULAR_PLACE_DETAILS'
}

export default actions