/* eslint-disable prettier/prettier */
const hotelActions = {
    GET_HOTEL_SEARCH: 'GET_HOTEL_SEARCH',
    SET_HOTEL_SEARCH: 'SET_HOTEL_SEARCH',
    GET_HOTEL_FILTER: 'GET_HOTEL_FILTER',
    SET_HOTEL_FILTER: 'SET_HOTEL_FILTER',
    SET_HOTEL_SESSION_ID:'SET_HOTEL_SESSION_ID',
    GET_SELECT_NAME:'GET_SELECT_NAME',
    SET_SELECT_NAME:'SET_SELECT_NAME',
    GET_HOTEL_ROOM_TYPE:'GET_HOTEL_ROOM_TYPE',
    SET_HOTEL_ROOM_TYPE:'SET_HOTEL_ROOM_TYPE',
    SET_ROOM_GUEST_PLACE:'SET_ROOM_GUEST_PLACE',
    SET_HOTEL_BOOKING:'SET_HOTEL_BOOKING',
    SET_HOTEL_BOOKING_DETAIL:'SET_HOTEL_BOOKING_DETAIL',
    GET_HOTEL_BOOKING_DETAIL:'GET_HOTEL_BOOKING_DETAIL',
    SET_HOTEL_FILTER:'SET_HOTEL_FILTER',
    GET_HOTEL_FILTER:'GET_HOTEL_FILTER'
}

export default hotelActions