/* eslint-disable prettier/prettier */
const hotelActions = {
    GET_HOTEL_SEARCH: 'GET_HOTEL_SEARCH',
    SET_HOTEL_SEARCH: 'SET_HOTEL_SEARCH',
    GET_HOTEL_FILTER: 'GET_HOTEL_FILTER',
    SET_HOTEL_FILTER: 'SET_HOTEL_FILTER',
    SET_HOTEL_SESSION_ID:'SET_HOTEL_SESSION_ID',
    GET_SELECT_NAME:'GET_SELECT_NAME',
    SET_SELECT_NAME:'SET_SELECT_NAME'
}

export default hotelActions